IF DB_ID('GestaoFunc') IS NULL
BEGIN
  CREATE DATABASE GestaoFunc;
END
GO

USE GestaoFunc;
GO

IF OBJECT_ID('dbo.Employees') IS NULL
BEGIN
  CREATE TABLE dbo.Employees (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(120) NOT NULL,
    CPF  NVARCHAR(20) NOT NULL UNIQUE,
    Posto NVARCHAR(80) NULL,
    Admissao DATE NULL,
    Score INT NOT NULL CONSTRAINT DF_Employees_Score DEFAULT (1000)
  );
END
GO

IF OBJECT_ID('dbo.Evaluations') IS NULL
BEGIN
  CREATE TABLE dbo.Evaluations (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EmployeeId INT NOT NULL FOREIGN KEY REFERENCES dbo.Employees(Id) ON DELETE CASCADE,
    Tipo NVARCHAR(40) NOT NULL,
    Descricao NVARCHAR(400) NULL,
    Points INT NOT NULL,
    CreatedAt DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

IF OBJECT_ID('dbo.AdminRecords') IS NULL
BEGIN
  CREATE TABLE dbo.AdminRecords (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EmployeeId INT NOT NULL FOREIGN KEY REFERENCES dbo.Employees(Id) ON DELETE CASCADE,
    Tipo NVARCHAR(60) NOT NULL,
    Descricao NVARCHAR(400) NULL,
    CreatedAt DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

